# Generated by Django 4.2 on 2023-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
