# Generated by Django 4.2 on 2023-04-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
        migrations.AlterUniqueTogether(
            name="userfollowing",
            unique_together={("following", "followers")},
        ),
    ]
