# Generated by Django 4.2 on 2023-04-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_follower_remove_following_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
