# Generated by Django 4.2 on 2023-04-23 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_follower_following_user_alter_follower_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="following_user",
            new_name="follower",
        ),
    ]
