# Generated by Django 4.2 on 2023-04-23 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_follower_user_alter_following_following_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("user", "following_user")},
        ),
        migrations.AlterUniqueTogether(
            name="following",
            unique_together={("user", "following_user")},
        ),
    ]
