# Generated by Django 4.2 on 2023-04-23 11:44

from django.db import migrations, models
import user.user_manager


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_follower_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.user_manager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
