# Generated by Django 4.2 on 2023-04-22 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_post_author_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
