# Generated by Django 4.2 on 2023-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ManyToManyField(
                null=True, related_name="posts", to="content.image"
            ),
        ),
    ]
