# Generated by Django 4.2 on 2023-04-22 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_remove_image_post_post_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
