# Generated by Django 4.2 on 2023-04-23 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_remove_post_images_post_image"),
    ]

    operations = []
