# Generated by Django 4.2 on 2023-04-23 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_auto_20230423_1048"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image",
            new_name="images",
        ),
    ]
