# Generated by Django 4.2 on 2023-04-23 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0014_alter_post_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="content.image"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "user")},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                (
                    "posts",
                    models.ManyToManyField(related_name="tags", to="content.post"),
                ),
            ],
        ),
    ]
