# Generated by Django 4.2 on 2023-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="content.tag"
            ),
        ),
    ]
