# Generated by Django 4.2 on 2023-04-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_remove_tag_posts_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="content.image"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="content.tag"
            ),
        ),
    ]
